export const ActionTypes = {
  // USER ACTIONS
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SIGN_UP: 'SIGN_UP',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  // EVENT ACTIONS
  SEARCH_EVENT_PARAMS: 'SEARCH_EVENT_PARAMS',
  SEARCHED_EVENTS: 'SEARCHED_EVENTS',
  // CLUB ACTIONS
  SEARCH_CLUB_PARAMS: 'SEARCH_CLUB_PARAMS',
  SEARCHED_CLUBS: 'SEARCHED_CLUBS',
  // GIG ACTIONS
  SEARCH_GIG_PARAMS: 'SEARCH_GIG_PARAMS',
  SEACHED_GIGS: 'SEACHED_GIGS'
};
